require File.expand_path(File.dirname(__FILE__) + '/spec_helper')

describe MultiMail do
  describe '#autoresponse?' do
    before :each do
      @message = Mail.new
    end

    it 'should return false if the message is not an autoresponse' do
      MultiMail.autoresponse?(@message).should == false
    end

    it 'should return true if an autoresponder header is found' do
      @message['X-Autogenerated'] = 'value'
      MultiMail.autoresponse?(@message).should == true
    end

    it 'should return true if an autoresponder value is found' do
      @message['Return-Path'] = '<>'
      MultiMail.autoresponse?(@message).should == true
    end

    it 'should return true if Auto-Submitted is not "no"' do
      @message['Auto-Submitted'] = 'auto-replied'
      MultiMail.autoresponse?(@message).should == true
    end

    it 'should return false if Auto-Submitted is "no"' do
      @message['Auto-Submitted'] = 'no'
      MultiMail.autoresponse?(@message).should == false
    end

    it 'should return true if the subject matches a regular expression' do
      @message.subject = 'Out of Office AutoReply: Subject'
      MultiMail.autoresponse?(@message).should == true
    end
  end
end
